### ISSUE TITLE
Support Swift 2.0 `throws`?

### ISSUE THREAD

**Issue by Bouke** [nestproject/Nest#10]
Allow handlers to be marked as `throws` and then catch this error, and return 500 response. This allows for easier error handler in the implementing handlers.

**Comment by kylef** [comment]
Hi @Bouke, thanks for the feedback.

I think applications should catch their own, internal errors, and display a helpful message. The decision is up to the application to decide what helpful means in their own context.

Ideally, you would never see a 500 internal server error, because there would never be any internal server errors. Instead correctly handled errors resulting in the correct error code.

For example, using Inquiline (a framework that provides a base implementation of a Nest ResultType) provides the following:

```swift
Response(.MethodNotAllowed)
Response(.RequestTimeout)
Response(.UnsupportedMediaType)
Response(.NotImplemented)
Response(.HTTPVersionNotSupported)
```

However, any Nest compatible framework or Nest server may allow errors to be thrown, I just don't think it should be in the Nest specification. This may certainly help with debugging.

For example, there could be a "DebugMiddleware" to catch unknown errors and wrap a throwing application:

```swift
import Inquiline

class DebugMiddleware {
    let closure:RequestType throws -> ResponseType

    init(closure:RequestType throws -> ResponseType) {
        self.closure = closure
    }
    
    func handler(request:RequestType) -> ResponseType {
        do {
            return closure(request)
        } catch InvalidCredentials {
            return Response(.Forbidden)
        } catch {
            return Response(.InternalServerError, body: "some pretty HTML template")
        }
    }
}

// Usage
func throwingApplication(request:RequestType) throws -> ResponseType {
    throw ItsAllBroken
}

serve(DebugMiddleware(throwingApplication).handler)
```

What do you think?
