### ISSUE TITLE
About the body property of both Request and Response

### ISSUE THREAD

**Issue by Evertt** [nestproject/Nest#18]
Why is it an optional string?

If it's a string and it's empty, then it can just be an empty string right? It makes handling the body just a bit more easy, one can always print an empty string without having to unpack it first, like one has to do with an optional.

And why is it a string in the first place? Wouldn't it be better to make it a stream? So one can send and receive large amounts of data?

**Comment by kylef** [comment]
@Evertt For the purposes of moving Nest forward, the initial draft used a string for simplicity. There has always been plans for it to be a stream. There is a proposal at https://github.com/nestproject/neps/blob/master/draft/0002-streamable-bodies.md which addresses both of your points. Would you please take a look and let me know if this solves all your concerns or if you have any alternative suggestions.

Regards,

Kyle

**Comment by Evertt** [comment]
I still don't get why the body should then be an optional payload type. I get why the `next` method of a payload type should return an optional nil, but why does the body of a request / response need to be an *optional* payload type? It can just be an empty payload type right?

**Comment by kylef** [comment]
The proposal in NEP2 only makes the body of the response optional and not that of the request. I think this makes sense as otherwise a client will need to create and return a PayloadType implementation even for cases where there is no payload.

**Comment by kylef** [comment]
Can you please elaborate on what the problems you see with making PayloadType optional in the ResponseType? To me it just adds more work for client implementors.

**Comment by Evertt** [comment]
> To me, making it non-optional just adds more work for client implementors.

That's funny, I think it's the other way around. Making it optional adds more work, doesn't it?

It makes the difference between this:

```swift
if let body = self.body {
    while let byte = body.next() {
        sendByteToBrowser(byte)
    }
}
```

and

```swift
while let byte = body.next() {
    sendByteToBrowser(byte)
}
```

See? Since the `next` method already returns an optional, you don't need to double that by making the body an optional as well, since I think it does nothing more than add more work.

**Comment by kylef** [comment]
Sure, it's *marginally* less simpler for server implementors. However it's far simpler for application implementors, which I expect that most people using Nest will be. I believe since most people will be writing application, and not servers for Nest that we should focus on easy of use for application implementation.

Here's example for building a 204 response with the body being optional:

```swift
struct EmptyResponse : ResponseType {
  let statusLine = "204 NO CONTENT"
  let headers: [Header] = []
  let body: PayloadType? = nil
}
```

Whereas, if it was not optional, am application would need to implement a PayloadType:

```swift
struct EmptyPayload : PayloadType {
  mutating func next() -> Int8? {
    return nil
  }
}

struct EmptyResponse : ResponseType {
  let statusLine = "204 NO CONTENT"
  let headers: [Header] = []
  let body: PayloadType = EmptyPayload()
}
```

Which is significantly more code.

---

Also, both of your examples may be wrong. As a response type's body is read-only and the next function is mutating. A server implementation would need to create a mutable version in order to iterate over the payload. Grabbing a PayloadType each time *may* result in an infinite loop if the application's response type's body returns a new payload at 0-index.

So, it's really:

```swift
var body = request.body
while let byte = body?.next() {
    sendByteToBrowser(byte)
}
```

Vs:

```swift
var body = request.body
while let byte = body.next() {
    sendByteToBrowser(byte)
}
```

Where there is marginal difference.

**Comment by Evertt** [comment]
Thanks, you've convinced me. :-)
I'm happy you spend the time to answer my objections even though my objections are apparently not very thought-through.
