### ISSUE TITLE
Caveat Implementor

### ISSUE THREAD

**Issue by mattt** [nestproject/Nest#6]
I think the project of creating a unified HTTP semantics in Swift is laudable and exciting. However, I would strongly caution you against using Rack as inspiration for the actual implementation.

Rack is minimal as in "lowest-common-denominator", not as in "simple" or "elegant". It is the way it is because it had to cater to all of the existing web frameworks and servers in order to get any traction, and did so in a way that had to contend with Ruby's dynamic type system and anemic static library. It was wildly successful and important in unifying Ruby's web ecosystem at a critical moment, but its design trade-offs have had serious consequences on future implementation.

While this _looks_ elegant:

```ruby
app = Proc.new do |env|
    ['200', {'Content-Type' => 'text/html'}, ['A barebones rack app.']]
end
```

...the translation to Swift gives off a smell.

```swift
func application(env:[String:AnyObject]) -> (String, [(String, String)], String?) {
    return ("200 OK", [("Content-Type", "text/plain")], "Hello World")
}
```

First off, why represent a response with a tuple? Surely a higher-level abstraction like a `Response` struct would be nicer to work with. Although an HTTP message can be thought of merely as a string, Stringly-typing everything as such means opting out of any insight the compiler might be able to provide. By not being able to model the body of a response as a stream, the abstraction dooms itself to failure with real-world usage.

But my real sticking point with Rack, and similarly with this proposal, is that `env` / `environ` argument passed into the closure. What is that, even?! Again, the best Ruby can do in this situation is model this as an arbitrary hash of string keys like `'CONTENT_TYPE'` and `rack.request.method`. [`Rack::Request`](http://rack.rubyforge.org/doc/Rack/Request.html) is nothing but a wrapper on top of this hash, providing readonly convenience access to the information needed to handle a request. Surely, a first-class `Request` struct could do more than an `[String:AnyObject]`.

**We can do so much better with Swift**

For your consideration:

- Statically-typed value types representing networking primitives, instead of a stringly-typed bag-of-data approach to modeling.
- Abstractions that take advantage of high-level Swift standard library constructs, like sequences and streams.
- Functional programming approach to middleware, where it's about the successive application of functional transformations, rather than calling instances of application objects.

Again, I'm extremely excited to see what will be done in this space. I just want to caution against the appropriation of Rack's design when much better options are available to us now.

**Comment by kylef** [comment]
Sorry for not getting back to this one yet. Promise I'll find time to respond with feedback soon.

**Comment by kylef** [comment]
Here's my quick thought on this @mattt, would be happy to get together to talk about this in more detail.

> However, I would strongly caution you against using Rack as inspiration for the actual implementation.

I think Rack is a bad example to compare Nest to, since Rack itself is both an interface and a Ruby library. Nest by design is only an interface and the goal is that you can use the Nest interface without depending on any kind of Nest framework. Rack also has various problems in it’s design and doesn’t allow you to exercise everything from the HTTP Specification (example: status lines etc).

---

> First off, why represent a response with a tuple? Surely a higher-level abstraction like a Response struct would be nicer to work with.

This would require a shared framework which supplies these structures or protocols and may require the server and web application to be compiled together, this goes against the project goals:

> "The interface must not make use any external frameworks and only depend on core Swift language features." -- README/Goals

One of the primary goals of the Nest interface, is that it doesn't depend on any code, the interface should be completely expressed using Swift standard library types. This allows you to compile a web application and a web server independently and they have no shared code. When we start adding structures and objects to be passed around this is no longer possible.

Request and Response protocols/structures may also become opinionated and should probably just belong on a framework that uses Nest (See werkzeug and WSGI).

---

> Although an HTTP message can be thought of merely as a string, Stringly-typing everything as such means opting out of any insight the compiler might be able to provide. By not being able to model the body of a response as a stream, the abstraction dooms itself to failure with real-world usage.

I really do wish we could have some kind of stream, I agree, it's critical that Nest supports streaming response bodies. I was planning to replace the string with some form of generator (see #2).

---

> Functional programming approach to middleware, where it's about the successive application of functional transformations, rather than calling instances of application objects.

Exactly, check out some of the Nest compatible middlewares.

- URL Routing: https://github.com/kylef/Turnstone and this PR add generic support for Request/Response types https://github.com/kylef/Turnstone/pull/1
- HTTP Auth: https://github.com/nestproject/Padlock

**Comment by kylef** [comment]
Regarding the response body, I don't believe it should be a string at all, but instead some kind of structure for expressing data (such as NSData, but this isn't a Swift standard type).
